name: 12 - Working with outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.export.outputs.status }}
      output1: ${{ steps.export.outputs.output1 }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"

      - name: Build
        run: echo "Building... (status: ${{ inputs.build-status }})"

      - name: Export outputs
        id: export
        run: |
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        if: ${{ needs.build.outputs.build-status == 'success' }}
        run: echo "Deploying ðŸš€"

      - name: Print Outputs
        run: |
          echo "Output 1: ${{ needs.build.outputs.output1 }}"
          echo "Build status: ${{ needs.build.outputs.build-status }}"
